language: scala
scala:
- 2.11.1
jdk:
- oraclejdk8
script:
- cd $TRAVIS_BUILD_DIR
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  global:
  - secure: wvrLgx0Ohx6YWmED5hkXi3l17LCZF1Zi6G8eD0zbP3zBE+Szj1ynvsOXHddP4eq99mpN7Yrp1GHVR2LjOUo5fSldXbDwCLxSZHzSO42xiOqaaRypvitCPcM85o+Q0vFe981BADfWFtarlQ4aVwmy1PWkBdv/fJTf81P/hBq1/m6OsLuPMqrUSgpA1WwsHb44Ao7kbbQt+NWoKLRX3Fvf9rUnVG6HTln/xOCffs3bqvt+0YPt6O30eTogUv5c5NiGi+016cy3Vd+WHrr+dx6NNfrNi4g5o1CYZ1pNE1YK53HFk64BYPP04zfKOn2ftRxk7DjNt1xR0xsBBVU7p06ZqJdm3uZ6VT7cidG8PR3ar++fPXjByHWO3y/jIlRNRmZK6Y6p3iUEIuW168lCanAdGtwBDQNsIkUkvZoDF57D8un9rDdCgHvCdtleQZmt7ZwqqQNSdfA5IzH9aNLUcHaUX7qk1Y4HXgVGiZTtlEpRjScV3VP0fSb68aGmOI8ePEHO3LW7t3U4hc0GUhZBYsO57DNmFe2XDO2PwcZcrLOBY+UIv3twr4oLUx1gbUezfGGqFEMy/xEL2KV2Qu4KbUWE+n7+HKHh8uzeL7St7OEnlRVaxAcvtznfa7QK0dXQEQb50tfKFy/89gU/qirdxnP6FlatSErO3/Hsq5/D+Hg4RLs=
  - secure: gp8tmQ4Kfkz/rYUhcjoeyRW0tVjnxWv4UuVyzVlWMY7LektSAJR+JKqOcXOer3qFWTVo2p9cq6+LSOPlGiN3QeLcad7EBhivQitYus28StvswaLhrYGV+/JNWjaI0GAY5TyZahUYsrGdCh2xWMMHVNQTp/hYUULSyyQ9xwB4KJkXvUTREy0cDHoXj3rk9l2yZYryu/RoPRd2UVT6yj8CHLKW7pkKHEOcuqVYh9GwfcpgJdLdKaJiMCctZK1pPW8UFldkXulHoAbxBJzLwPthbQMPxKf9F4zJOmc9HlnFVJecmyaf1g3vNQlzSet87pIJHh8/2kTpWU94KysNMPtRqPda4omg+c73x3pffkgSDQEnmHhGi6cGDX8ID9Mhwg664DDa2JHh2iBRL2Q5pEkdODZl64F7c+6yEQosxVdDAi1IfXbY8LphlDtk8BeO8aELCSyJ/DRhorwuc6GzLvR0akuFBCywjzaj+xP+UffmbTIvh8WHWd5AqthVPI3bE+ztapgjkrLYfM5tLtDgpqOza/96zQPEfQhmcFOdeMtMqAKoOCd8wxgxneB28vN8OAIsR3lVhTWFDxtRFgeIR1iwzeQbXmT8TywjmJOAQcXSWe25srw0R1TC/pl73g2CYrMl1vMTfQ2CqF2k0qabydNYr1z5OStGSk3wtcEBELAFX6k=
  - secure: e5nukDq8Qv/4k/SYjfUXXUEdqg/VAh9OcPYsz7e2zgKr82xuVa4gHrV+JeZX1RLBz5+a6xV6ZQgOY2FH5RSsjiCuBZz8ENPr4O1lRZTrry5xYhVVI7GJXgNlaFmEM0KV97HHDQ64NL2FmEHNw7DjegxPto77rbD/4UYJB9mak+0/3rFIE2tD9JW59tu/olmqdQ5kcJXIU0F7pQ2XE+pKSIK98zoWj4fGBGxN5ndBW59ZI3YYeCK5LPDyaKjNAb+DvJ8XSRIMwmVNrHJy0l94kK3VAFx9wmKbcv72rfM0Ms6bgTMafUg8AGhGTQkNaQtYIIznoRO3UYNYreMEIYSew2ceBzid7EMLxq+lqfabMaIV1D0ngI4gEBtpz6D0mcXkonsdQSiAT9t+cZ08Uq1s0v+0hhWhtl4ESxC8o7herIhjBCXYwS4nUGPAeDsUsT25z5aePtDLEuou/H0WR+jJS2AI/3mvaQGa0sQEaryH6R0ukQ4dknM5lXsIPultBN3ZgFrOmANoU9MabOJn6OZ9EqYv2YapQ31dxeIPBeTGPknUmBfuzG+/Bu+6G7OR4XBJzMQWaZZcLMBD7t7N/hssWeWScXHbfSI5WuvDXcEatQh0oZe4bJCaQHWgjrduMlrprcalw6bFbMLvK/KKCcrCQmJTGPOd48Lv7wBQwhZ8FHk=
services:
- mongodb
addons:
  sauce_connect:
    no_ssl_bump_domains: all
# https://github.com/travis-ci/travis-ci/issues/1476
after_success:
  - sbt dist
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG
branches:
  except:
    - /build-.+-\d{4}-\d{2}-\d{2}-.*/
deploy:
  - provider: heroku
    api_key:
      secure: r3qE7SMenfaxrHv9mHczyilMi7asBfewVe4a4MbIdcdMQXqQRZNVNaV+gtmRdc7owkNoea3zvQVeDETN4PbZlMOcVtjsDq1gGR3bU3AoeoIF7aSBr8mIU+0VdJ8lj7L8YjWOiZuLPjZYdw0BIuBHAu7kVaRZaGA1VqmHrT0TCGcTJo2VqWWyNS12P2/cKrDQ3uwqNOT+jz7owUoRhBx6nYtgbJW3LHryMrvQs8HCJQdiv79aNbJvL8ifcqFN2NoB1CrHoWHa0F7dt2jrFSvflYxGXz0wh70mF/H4XDmnyRdLUsUtcMrcbtBcUUCZbSYaCOIqW9F4RVd75ucY3AOC9BXLIs1n8OZOcZQ2wMKUOLWFl9tlMAT+NiBQFonnSgQli5WaIHa5zmiDrc3z2IV+SPdmiQ6RCWyxo+XbGpwAUApIh3qN30yEvR8BPCcNoFoUtvWuenQ44q+f89iz1UAw4fApVyMPtVKEJTKixJcWIMPMWT41xYeY6uO76XX7vNijc0n+17kjNK2RFtycPw5A+J0CkVIlfdpoIzQTLlnXdBYjrRCrpsDukhn8aJUljkLFhT6BAXyFWobjKDfPPa7iP1ig9oRZdSLJQ8zcsunRO1iUd42UJj4pyDnw0A/Cs3bOp4oLshWssmvXnupAMrf5uu5sNJpK4CWjybqxbdCf5mo=
    app: awale
    on:
      repo: YannMoisan/awale
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: iHdbfVaB1ULRcAdJjaT81x8yWTzqEvqbQKY85JiE26Z6nZj8vXVSirUz2DXWi+4nPQJRPlsQn055u2v++vn0yN3SupdoDRBCHzRuXfB3VWpkL7Y2CfVo8ZZOhf/j5bT8UbB6+1LNjreUJUtCFAUHdKV302MEm4zZJ4gZainqjAp0jxC7798eC7DEH5Z58ZSoM4JzzPRIP28lW1zlePqWwfoLJ+gV2DgyH2Y+aZaHZdneU7v4pS+Oh04fRDeE53aeGgxQTya0iyeEg4pKcedsCMF3vqhTimfTHaEjRxDjl9lOf1AXA1c5us10+RAPK4xNfzuh6/J2eArnNJzY1+2uPq86Lju3fNzMIevFECImB3T8HiuaFqM4Z41fGfPE854wqaXamsFwuwXI7PbNu1Y6s5gXABRhCTe1Gdgohj2WdtwvBqiYAR6q0Np9jqDjZPOVnVE5vr9KhJVsyVNCCeHbaIpCOUm4EzJ05knYCurfZ7g2bCxs6HlbGh8Rs1JSod6xXCfZkGroibB9prA0+fmD6IN+AsTXqyTZ7Cyx2spUdgi2ImO3vH6D9sPV6gy8vB3BxJlWTDTi9/i6BK/K3XAAeHrc6PgARPvfThhXU+2QJvV2I9sfyKFW2S4gKMzhlBzh4OaYzzD+LEukAPabM1e9OCcGyBnqwI5ajla8BwHYvnk=
    file: target/universal/awale-1.0-SNAPSHOT.zip
    on:
      repo: YannMoisan/awale
      tags: true
