language: scala
scala:
  - 2.11.1
jdk:
  - oraclejdk8

#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

script:
- cd $TRAVIS_BUILD_DIR
- sbt ++$TRAVIS_SCALA_VERSION test

#  encrypted SAUCE_USERNAME and SAUCE_ACCESS_KEY
env:
  global:
    - secure: wvrLgx0Ohx6YWmED5hkXi3l17LCZF1Zi6G8eD0zbP3zBE+Szj1ynvsOXHddP4eq99mpN7Yrp1GHVR2LjOUo5fSldXbDwCLxSZHzSO42xiOqaaRypvitCPcM85o+Q0vFe981BADfWFtarlQ4aVwmy1PWkBdv/fJTf81P/hBq1/m6OsLuPMqrUSgpA1WwsHb44Ao7kbbQt+NWoKLRX3Fvf9rUnVG6HTln/xOCffs3bqvt+0YPt6O30eTogUv5c5NiGi+016cy3Vd+WHrr+dx6NNfrNi4g5o1CYZ1pNE1YK53HFk64BYPP04zfKOn2ftRxk7DjNt1xR0xsBBVU7p06ZqJdm3uZ6VT7cidG8PR3ar++fPXjByHWO3y/jIlRNRmZK6Y6p3iUEIuW168lCanAdGtwBDQNsIkUkvZoDF57D8un9rDdCgHvCdtleQZmt7ZwqqQNSdfA5IzH9aNLUcHaUX7qk1Y4HXgVGiZTtlEpRjScV3VP0fSb68aGmOI8ePEHO3LW7t3U4hc0GUhZBYsO57DNmFe2XDO2PwcZcrLOBY+UIv3twr4oLUx1gbUezfGGqFEMy/xEL2KV2Qu4KbUWE+n7+HKHh8uzeL7St7OEnlRVaxAcvtznfa7QK0dXQEQb50tfKFy/89gU/qirdxnP6FlatSErO3/Hsq5/D+Hg4RLs=
    - secure: gp8tmQ4Kfkz/rYUhcjoeyRW0tVjnxWv4UuVyzVlWMY7LektSAJR+JKqOcXOer3qFWTVo2p9cq6+LSOPlGiN3QeLcad7EBhivQitYus28StvswaLhrYGV+/JNWjaI0GAY5TyZahUYsrGdCh2xWMMHVNQTp/hYUULSyyQ9xwB4KJkXvUTREy0cDHoXj3rk9l2yZYryu/RoPRd2UVT6yj8CHLKW7pkKHEOcuqVYh9GwfcpgJdLdKaJiMCctZK1pPW8UFldkXulHoAbxBJzLwPthbQMPxKf9F4zJOmc9HlnFVJecmyaf1g3vNQlzSet87pIJHh8/2kTpWU94KysNMPtRqPda4omg+c73x3pffkgSDQEnmHhGi6cGDX8ID9Mhwg664DDa2JHh2iBRL2Q5pEkdODZl64F7c+6yEQosxVdDAi1IfXbY8LphlDtk8BeO8aELCSyJ/DRhorwuc6GzLvR0akuFBCywjzaj+xP+UffmbTIvh8WHWd5AqthVPI3bE+ztapgjkrLYfM5tLtDgpqOza/96zQPEfQhmcFOdeMtMqAKoOCd8wxgxneB28vN8OAIsR3lVhTWFDxtRFgeIR1iwzeQbXmT8TywjmJOAQcXSWe25srw0R1TC/pl73g2CYrMl1vMTfQ2CqF2k0qabydNYr1z5OStGSk3wtcEBELAFX6k=

addons:
  sauce_connect: true
